name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-docker-desktop:
    name: Test Docker Desktop installation and start
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu22_16cores_64gb, macos-latest]
        build-url:
          [
            "latest",
            "https://desktop.docker.com/linux/main/amd64/122432/docker-desktop-4.24.0-amd64.deb",
          ]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Start Desktop
        uses: ./start
        timeout-minutes: 5
        with:
          docker-desktop-build-url: ${{ matrix.build-url }}

      - name: Docker Desktop version
        run: docker version >> $GITHUB_STEP_SUMMARY

      - name: Docker Desktop info
        run: docker info

      - name: Gather Diagnostics
        if: ${{ failure() }}
        run: /opt/docker-desktop/bin/com.docker.diagnose gather -upload
